version: '3'
services:

  server1:
    container_name: server1
    build: ./django
    command: uwsgi --ini django_uwsgi.ini
    expose:
      - "8000"
    networks: 
      - default
    tty: true
  proxy:
    container_name: nginx_proxy
    build: ./nginx
    command: service nginx start
    ports:
      - "8080:80"
    depends_on:
      - server1
    networks: 
      - default
    tty: true

networks:
  default:
     driver: bridge 
